project:
  type: website
  output-dir: docs

website:
  title: "Davi Rocha"
  description: "Data Scientist | Professor | Healthcare Analytics"
  
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Início
      - href: about.qmd
        text: Sobre
      - href: projetos/index.qmd
        text: Projetos
      - href: ensino/index.qmd        # ADICIONE ESTA LINHA
        text: Ensino                  # ADICIONE ESTA LINHA
    right:
      - icon: github
        href: https://github.com/davimatfacil
      - icon: linkedin  
        href: https://www.linkedin.com/in/davi-rocha-27a24b33/
      - icon: youtube
        href: https://www.youtube.com/@DaviRocha_ML
      - icon: envelope
        href: mailto:davimatfacil@gmail.com


  page-footer:
    center: "© 2026 Davi Rocha | Professor e Data Scientist "

format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true
    code-copy: true
    code-fold: false